### ISSUE TITLE
Result.flatMaps type signature is surprising

### ISSUE THREAD

**Issue by martinei** [spencerwi/Either.java#1]
map and FlatMap have basically the same Type Signature apart from Exception Handling, which is wrong.
```
public abstract <T> Result<T> map(Function<R,T> transformValue);
public abstract <T> Result<T> flatMap(ExceptionThrowingFunction<R,T> transformValue);
```
Compared to flatMap on Scalas Try (or pretty much any other Class with flatMap in any functional Language):
```
 flatMap[U](f: (T) ⇒ Try[U]): Try[U] 
```
I'd like to have a "real" flatMap Function. Catching Exceptions and translating to Result should be done by both, map and flatMap.

**Comment by spencerwi** [comment]
Ah, this is an oversight. Good catch.

Sorry for the long delay; I'm not sure why I didn't get a ping on Github for this.

**Comment by spencerwi** [comment]
Version 2.0.0 (just pushed to Sonatype OSS) fixes this issue.
