### ISSUE TITLE
Do you think you will implement Try?

### ISSUE THREAD

**Issue by dxxvi** [spencerwi/Either.java#12]
`public abstract class Try<A> extends Either<Throwable, A>` but then I don't know how to implement `Success` and `Failure`.

**Comment by spencerwi** [comment]
Hi @dxxvi! You might find that `Result.attempt(...)` already meets your needs. I'd recommend reading [the unit tests for Result](https://github.com/spencerwi/Either.java/blob/master/src/test/java/com/spencerwi/either/ResultTest.java) to see how `Result.attempt` works.
