### ISSUE TITLE
Wrong username in changelog

### ISSUE THREAD

**Issue by hamishlawson** [spencerwi/Either.java#15]
In the changelog my username is given as _hamishwilson_ instead of the correct _hamishlawson_

**Comment by spencerwi** [comment]
Shoot, sorry about that -- I dunno how I got that swapped around. I'll fix that!

**Comment by hamishlawson** [comment]
> Shoot, sorry about that -- I dunno how I got that swapped around. I'll fix that!

Thanks :-)
Hamish
