### ISSUE TITLE
Either contains 2 value pointers instead of 1

### ISSUE THREAD

**Issue by dejj** [spencerwi/Either.java#2]
What's the reason for using 2 value pointers per element instead of one:
```
public abstract class Either<L, R> {
    protected L leftValue;
    protected R rightValue;
```
It seems like every indirection via Either will double the required space for the pointers. Shy of a union type, you could have used java.lang.Object and cast it dynamically to L or R.

**Comment by spencerwi** [comment]
Hey, sorry I'm so late getting back to this! I dunno why I didn't get a notification on it.

Honestly, it's primarily just the typesafety concern you pointed out. I could pull out the duplication to halve the space usage.

**Comment by dejj** [comment]
It's been a while. I went and wrote an Either myself. This I ended up with:

    public interface Either<L,R>
    {
        enum Enum { Left, Right }

        class Left<L,R> implements Either<L,R>
        {
            L value;
            public Left (L left) { this.value = left; }

            public Enum which() { return Enum.Left; }
            public boolean isLeft() { return true; }
            public boolean isRight() { return false; }

            public L getLeft() { return value; }
            public R getRight() { throw new UnsupportedOperationException("Left.getRight() not supported"); }

            public <L_out> Either<L_out,R> mapLeft(F<L,L_out> f ) { return new Left<>(f.f(value)); }
            public <R_out> Either<L,R_out> mapRight(F<R,R_out> f ) { return (Left<L,R_out>)this; } // cast instead of rewrap to save overhead // { return new Left<>(value); }
        }
        class Right<L,R> implements Either<L,R>
        {
            R value;
            public Right (R right) { this.value = right; }

            public Enum which() { return Enum.Right; }
            public boolean isLeft() { return false; }
            public boolean isRight() { return true; }

            public L getLeft() { throw new UnsupportedOperationException("Right.getLeft() not supported"); }
            public R getRight() { return value; }

            public <L_out> Either<L_out,R> mapLeft(F<L,L_out> f ) { return (Right<L_out,R>)this; } // cast instead of rewrap to save overhead // { return new Right<>(value); }
            public <R_out> Either<L,R_out> mapRight(F<R,R_out> f ) { return new Right<>(f.f(value)); }
        }

        // Java 1.8
        //public static <L,R> Either<L,R> left(L left){ return new Left<>(left); }
        //public static <L,R> Either<L,R> right(R right){ return new Right<>(right); }

        // use in switch-statements
        Enum which();
        boolean isLeft();
        boolean isRight();

        // these methods save you from explicit casting and repeating the parameter types
        L getLeft();
        R getRight();

        <L_out> Either<L_out,R> mapLeft(F<L, L_out> f);
        <R_out> Either<L,R_out> mapRight(F<R, R_out> f);
    }


where ``F<T,R>.f`` is basically ``java.util.Function<T,R>.apply`` from Java 1.8

I didn't get rid of the unused type parameters, e.g. ``class Left<L> implements Either<L,Void>`` instead of ``class Left<L,R> implements Either<L,R>`` because they have to appear in the result types of ``mapLeft`` and ``mapRight``. If you don't need those methods, you can drop the types.

**Comment by spencerwi** [comment]
Thanks for the feedback! I eliminated the duplicate field in v1.2.1
