### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by arichiardi** [spencerwi/Either.java#6]
Hi @spencerwi,

I was wondering if you can think about and then add a license for this library (which is very nice and simple that's why I like it!).

Thank you very much!

**Comment by arichiardi** [comment]
Never mind, I found it, just not where I was thinking, not in the README :smile:

**Comment by spencerwi** [comment]
Glad you were able to find it! This project is MIT licensed. It's probably worth adding that detail to the README. I'll do that when I can. 

Glad you like the library!
