### ISSUE TITLE
Run method for Result

### ISSUE THREAD

**Issue by andy32323** [spencerwi/Either.java#8]
Hello,
I was very happy you made the effort to create this library.
Also I like how you added the _Result_-approach.

I am missing a run method for the _Result_ class.
There is one in the _Either_ so I will change my current usage of the library to the _Either_-Approach.

**Comment by spencerwi** [comment]
Hi, and thanks for the kind words, and for using this lib. I'll take a look at this request when I get a bit more time and see what I can figure out.

**Comment by spencerwi** [comment]
Hi @andy32323! I'm sorry it's taken so long to get back to you -- life has been a bit uncertain the past few weeks on my end.

Could I maybe understand your use-case a little more? Technically what you want is achievable with the `.map` method on `Result`, but I'm guessing you probably want "execute if `Ok`, throw if `Err`" behavior instead?

**Comment by andy32323** [comment]
I was looking for a method with the same signature as in the java.util.Optional::ifPresent. It takes a consumer of an ok-value and runs it, if its Ok. If its not Ok, nothing happens.

Example:
List<ParseResult> results = new ArrayList<>();
for (String input : args) {
parseArg(input).ifOk(results::add);
}

**Comment by andy32323** [comment]
Also there can be the same functionality for both Non-Ok and Ok values within one method call:

`parseArg(input).run(error -> reportError(error), results::add)`

**Comment by spencerwi** [comment]
Hi @andy32323! 

From what you've described, I could see three methods that make sense, let me know what you think:

```java
/**
 * Runs the acceptsOkValue function IF this is an Ok instead of an Err, passing in the value that "Ok" wraps.
 * Does not return a value. If you need to transform a Result<T>, use {@link #map} or {@link #flatMap}.
 */
public void ifOk(Consumer<T> acceptsOkValue);

/**
 * Runs the errorHandler function with the wrapped exception if this is an Err, or else runs 
 *  the okHandler function with the wrapped value if this is an Ok.
 * Does not return a value. If you need to extract a value using a pair of "extractors", see {@link #fold}.
 */
public void run(Consumer<Exception> errorHandler, Consumer<T> okHandler);

/**
 * Runs the okHandler with the wrapped value if this is an Ok, otherwise throws a NoSuchElementException.
 * @throws NoSuchElementException if this is an Err
 */
public void consumeOk(Consumer<T> okHandler);
```

Does that "shape" of things match your use-cases?

**Comment by andy32323** [comment]
Yes, 1) and 2) do shape the functionality I was looking for.

Method 3) looks like a variation of java.util.Optional::get with a consumer.
Instead of implementing 3), you could implement `get` and `getOrElseThrow` as in `java.util.Optional` or as attempted in https://github.com/spencerwi/Either.java/pull/9

If you have a method as `java.util.Optional::get`, the method 3) can be constructed in one line of code:
`consumer.apply(result.get());`

I prefer this approach over method 3) because it uses smaller building blocks of logic.

That will cover most of the use cases I can think of at the moment.

**Comment by spencerwi** [comment]
Hi @andy32323!

v2.4.0 has `Result.ifOk` and `Result.run` -- I just released it via Sonatype OSS, so it should be in maven central shortly.

Thanks for your feedback, and happy programming!

-Spencer
